{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ec41a4a8-774d-4c9b-90c5-404f054cbaeb",
   "metadata": {},
   "outputs": [],
   "source": [
    "# ============================================================\n",
    "# Cryptocurrency Forecasting App\n",
    "# OLS vs ARIMA vs GARCH\n",
    "# ============================================================\n",
    "\n",
    "import warnings\n",
    "warnings.filterwarnings(\"ignore\")\n",
    "\n",
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import yfinance as yf\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "from statsmodels.tsa.arima.model import ARIMA\n",
    "from arch import arch_model\n",
    "import statsmodels.api as sm\n",
    "from sklearn.metrics import mean_squared_error, mean_absolute_error\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# Page configuration\n",
    "# ------------------------------------------------------------\n",
    "st.set_page_config(page_title=\"Cryptocurrency Forecasting\", layout=\"wide\")\n",
    "st.title(\"Cryptocurrency Forecasting\")\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# Sidebar\n",
    "# ------------------------------------------------------------\n",
    "st.sidebar.header(\"Settings\")\n",
    "\n",
    "crypto_map = {\n",
    "    \"Bitcoin\": \"BTC-USD\",\n",
    "    \"Ethereum\": \"ETH-USD\",\n",
    "    \"Polkadot\": \"DOT-USD\"\n",
    "}\n",
    "\n",
    "crypto_name = st.sidebar.selectbox(\n",
    "    \"Select Cryptocurrency:\", list(crypto_map.keys())\n",
    ")\n",
    "symbol = crypto_map[crypto_name]\n",
    "\n",
    "start_date = st.sidebar.date_input(\n",
    "    \"Start Date\", pd.to_datetime(\"2023-01-01\")\n",
    ")\n",
    "end_date = st.sidebar.date_input(\n",
    "    \"End Date\", pd.to_datetime(\"2023-12-31\")\n",
    ")\n",
    "\n",
    "horizon = st.sidebar.number_input(\n",
    "    \"Forecast Horizon (Days):\", min_value=7, max_value=90, value=30\n",
    ")\n",
    "\n",
    "run = st.sidebar.button(\"Run Forecast\")\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# Data download\n",
    "# ------------------------------------------------------------\n",
    "@st.cache_data\n",
    "def load_data(symbol, start, end):\n",
    "    df = yf.download(symbol, start=start, end=end)\n",
    "    df = df[[\"Close\"]].dropna()\n",
    "    return df\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# Models\n",
    "# ------------------------------------------------------------\n",
    "def ols_ar_forecast(series, steps):\n",
    "    returns = np.log(series).diff().dropna()\n",
    "\n",
    "    X = sm.add_constant(returns.shift(1).dropna())\n",
    "    y = returns.iloc[1:]\n",
    "\n",
    "    model = sm.OLS(y, X).fit()\n",
    "\n",
    "    last_ret = returns.iloc[-1]\n",
    "    preds = []\n",
    "\n",
    "    for _ in range(steps):\n",
    "        r_hat = model.params.iloc[0] + model.params.iloc[1] * last_ret\n",
    "        preds.append(r_hat)\n",
    "        last_ret = r_hat\n",
    "\n",
    "    prices = series.iloc[-1] * np.exp(np.cumsum(preds))\n",
    "    prices.index = series.index[-steps:]\n",
    "\n",
    "    return prices, model\n",
    "\n",
    "def arima_forecast(series, steps):\n",
    "    model = ARIMA(series, order=(1, 1, 1)).fit()\n",
    "    forecast = model.forecast(steps=steps)\n",
    "    return forecast, model\n",
    "\n",
    "def garch_forecast(series, steps):\n",
    "    returns = 100 * np.log(series).diff().dropna()\n",
    "    model = arch_model(returns, vol=\"Garch\", p=1, q=1)\n",
    "    res = model.fit(disp=\"off\")\n",
    "    vol = np.sqrt(res.forecast(horizon=steps).variance.values[-1])\n",
    "    return vol, res\n",
    "\n",
    "# ------------------------------------------------------------\n",
    "# Run app\n",
    "# ------------------------------------------------------------\n",
    "if run:\n",
    "    data = load_data(symbol, start_date, end_date)\n",
    "    close = data[\"Close\"]\n",
    "\n",
    "    train_size = int(len(close) * 0.8)\n",
    "    train = close.iloc[:train_size]\n",
    "    test = close.iloc[train_size:]\n",
    "\n",
    "    # Forecasts\n",
    "    ols_pred, _ = ols_ar_forecast(train, len(test))\n",
    "    arima_pred, _ = arima_forecast(train, len(test))\n",
    "    garch_vol, _ = garch_forecast(train, horizon)\n",
    "\n",
    "    # Errors\n",
    "    rmse_ols = mean_squared_error(test, ols_pred, squared=False)\n",
    "    rmse_arima = mean_squared_error(test, arima_pred, squared=False)\n",
    "\n",
    "    mae_ols = mean_absolute_error(test, ols_pred)\n",
    "    mae_arima = mean_absolute_error(test, arima_pred)\n",
    "\n",
    "    # --------------------------------------------------------\n",
    "    # Layout\n",
    "    # --------------------------------------------------------\n",
    "    col1, col2 = st.columns([3, 2])\n",
    "\n",
    "    with col1:\n",
    "        st.subheader(\"Price and Forecast\")\n",
    "        fig, ax = plt.subplots(figsize=(10, 4))\n",
    "        ax.plot(close, label=\"Actual\")\n",
    "        ax.plot(test.index, ols_pred, label=\"OLS Forecast\")\n",
    "        ax.plot(test.index, arima_pred, label=\"ARIMA Forecast\")\n",
    "        ax.legend()\n",
    "        ax.set_ylabel(\"Price (USD)\")\n",
    "        st.pyplot(fig)\n",
    "\n",
    "    with col2:\n",
    "        st.subheader(\"Model Evaluation\")\n",
    "        eval_df = pd.DataFrame(\n",
    "            {\n",
    "                \"RMSE\": [rmse_ols, rmse_arima, np.nan],\n",
    "                \"MAE\": [mae_ols, mae_arima, np.nan],\n",
    "            },\n",
    "            index=[\"OLS\", \"ARIMA\", \"GARCH\"],\n",
    "        )\n",
    "        st.dataframe(eval_df.style.format(\"{:.3f}\"))\n",
    "\n",
    "    st.subheader(\"GARCH Volatility Forecast\")\n",
    "    fig2, ax2 = plt.subplots(figsize=(10, 3))\n",
    "    ax2.plot(garch_vol)\n",
    "    ax2.set_ylabel(\"Volatility\")\n",
    "    st.pyplot(fig2)\n",
    "\n",
    "else:\n",
    "    st.info(\"👈 Select parameters and click **Run Forecast**\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
